language: php

sudo: required

services:
  - docker

php:
  - 7.2
  - 7.3
  - 7.4

branches:
  only:
  - /.*/

before_script: PHP_IMAGE="php:${TRAVIS_PHP_VERSION}-cli" docker-composer up -d

script: ./scripts/common/run-tests.sh

after_script: docker-composer down

after_success: bash <(curl -s https://codecov.io/bash)
