version: '3'
services:
  # This service is a basic development environment for the google-ads-php project.
  # It can be extended with more features, e.g., logs, debugging.
  google-ads-php:
    # Set the user to be used in the container.
    user: ${USER_GROUP_ID}

    build:
      # Use the Dockerfile that is sitting in the same directory.
      # Tip: refer to its content for more detail, e.g., how to use the arguments.
      context: .
      args:
        PHP_IMAGE: ${PHP_IMAGE}
        WORK_DIR: ${WORK_DIR}
        MAKEFLAGS: ${MAKEFLAGS}
        PROTOBUF_USE_PHP_EXTENSION: ${PROTOBUF_USE_PHP_EXTENSION}
        PROTOBUF_VERSION: ${PROTOBUF_VERSION}
        PROTOBUF_SRC_REPO: ${PROTOBUF_SRC_REPO}
        PROTOBUF_SRC_BRANCH: ${PROTOBUF_SRC_BRANCH}
        GRPC_USE_PHP_EXTENSION: ${GRPC_USE_PHP_EXTENSION}
        GRPC_VERSION: ${GRPC_VERSION}
        GRPC_SRC_REPO: ${GRPC_SRC_REPO}
        GRPC_SRC_BRANCH: ${GRPC_SRC_BRANCH}
        SRC_REPO: ${SRC_REPO}
        SRC_BRANCH: ${SRC_BRANCH}
        COMPOSER_MIRROR_PATH_REPOS: ${COMPOSER_MIRROR_PATH_REPOS}
        COMPOSER_NO_INTERACTION: ${COMPOSER_NO_INTERACTION}
        COMPOSER_INSTALL_UPDATE_ARGS: ${COMPOSER_INSTALL_UPDATE_ARGS}
    volumes:
      - ${SRC_DIR}:${WORK_DIR}
    command: ${COMMAND}
